GET http://localhost:5266/games

###
GET http://localhost:5266/games/4

###
POST http://localhost:5266/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5266/games/1
Content-Type: application/json

{    
    "name": "Lost Ark Mokoko Edition",
    "genre": "MMORPG",
    "price": 9.99,
    "releaseDate": "2018-11-18"
}


###
DELETE http://localhost:5266/games/2
